### ISSUE TITLE
Define the timezone

### ISSUE THREAD

**Issue by lucasdcrk** [electerious/Ackee#88] opened 2020-04-08 00:00 UTC
Hi!

I noticed that the docker container was not using the server's timezone, how can I define the timezone?

![OtKA.png](https://i.apo.pm/s/OtKA.png)
![Ol6j.png](https://i.apo.pm/s/Ol6j.png)

The total visit count is 0 for today and if I visit the website before 2AM it adds up to yesterday's stats which indicate it's a timezone problem.

**Comment by electerious** [comment] 2020-04-08 15:27
I've never adjust the timezone manually as everything was working correctly out of the box. I guess that this issue is Docker related and that you will get more answers on stackoverflow.com.

Please let me know when the time is correct on the server, but not in Ackee :)

**Comment by lucasdcrk** [comment] 2020-04-08 23:14
I was thinking it was docker related but I set the correct timezone on both the Ackee and mongo containers and had the same issue

I inspected the network requests and saw that the dates were UTC
![O5Yg.png](https://i.apo.pm/s/O5Yg.png)
(It was 01:06AM)

I don't understand from where the issue could come

**Comment by electerious** [comment] 2020-04-19 18:35
What I know so far:

The problem is that the server timezone and browser timezone aren't in sync. Ackee creates the date of new records using `Date.now()` on the server => `Date.now()` returns a timestamp => Timestamps are UTC.

> The definition of UNIX timestamp is timezone independent. The timestamp is the number of seconds (or milliseconds) elapsed since an absolute point in time, midnight of Jan 1 1970 in UTC time.

The API responses are already grouped (UTC based). The problem is that the client uses the local timezone/time to build the UI.

We could replace the `new Date()` on the client to use UTC:

```js
const now = new Date()
const utc = new Date(now.getTime() + now.getTimezoneOffset() * 60000)
```

… but no one wants to see the wrong timezone. We therefore need to tell the server the timezone of the client. This way the data would be correct no matter from where you view your stats.

I don't know if this is the best way, but it seems to be a solution.

**Comment by electerious** [comment] 2020-04-19 18:38
The question is: What's the correct timezone to display in the UI? The timezone from the server or the timezone from the client?

**Comment by BetaHuhn** [comment] 2020-04-21 16:30
Noticed this issue last night to. After midnight all new stats where listed as the previous day.
> What's the correct timezone to display in the UI? The timezone from the server or the timezone from the client?

I think the UI should display the timezone of the client. I want to know when something occurred in my local time not the servers.

**Comment by lucasdcrk** [comment] 2020-04-21 16:43
The best way would be to use the client's TZ I think. Perhaps include the timezone in the dashboard GET requests ![chWk.png](https://i.apo.pm/s/chWk.png)

**Comment by electerious** [comment] 2020-07-19 16:40
This was painful. It took five hours to fully understand how dates behave and how MongoDB deals with them. I really hope that I never have to work on this again 😃

This files contains a summary: https://github.com/electerious/Ackee/blob/9e7e5f5bef152651cd6eddcfe64dfd57f43c719c/src/utils/createDate.js#L9

It's hard to test, so I can't say that it's 100% correct and fixed. It can be tested on the `develop` branch, but don't update your production environment as v2 is a big rewrite and still untested.

**Comment by electerious** [comment] 2020-08-09 17:32
I've done another painful timezone debugging session, because it turned out that my fixes didn't solve the problem. The newest version is now ready to test and I need your feedback.

Here's how to update: https://github.com/electerious/Ackee/issues/129#issuecomment-667683855

BTW: It's the last issue and v2.0 is almost ready. Please let me know if all issues are fixed!

**Comment by electerious** [comment] 2020-08-15 12:52
@lucasdcrk Can you confirm that the fix is working?

**Comment by lucasdcrk** [comment] 2020-08-24 10:19
I will check tonight ^^

**Comment by electerious** [comment] 2020-09-04 16:03
Will close this issue for now as I think that it should be fixed. Let me know if that's not the case :)

**Closed by electerious** 2020-09-04 16:03 UTC
