### ISSUE TITLE
Installation problem with npm

### ISSUE THREAD

**Issue by creotip** [electerious/Ackee#26] opened 2015-06-02 10:14 UTC
> Ackee@1.0.0 preinstall C:\Users\ruslane\Downloads
> bower install

bower ENOENT        No bower.json present

npm ERR! Ackee@1.0.0 preinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Ackee@1.0.0 preinstall script.
npm ERR! This is most likely a problem with the Ackee package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls Ackee
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\ruslane\Downloads\Ackee-master
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\ruslane\Downloads\Ackee-master\npm-debug.log
npm ERR! not ok code 0

**Comment by electerious** [comment] 2015-06-04 16:34
Not sure what's causing this problem. "bower ENOENT No bower.json present" doesn't sounds correct. The file is in the folder.

**Comment by electerious** [comment] 2015-12-06 20:25
Can't reproduce. Closing the issue for now.

**Closed by electerious** 2015-12-06 20:25 UTC
