### ISSUE TITLE
Can't load sizes in Ackee v3

### ISSUE THREAD

**Issue by productfrontenddeveloper** [electerious/Ackee#217] opened 2021-01-21 16:37 UTC
Cannot return null for non-nullable field Size.id.
/index.js:31:15097
asyncFunctionResume@[native code]
[native code]
promiseReactionJobWithoutPromise@[native code]

**Comment by electerious** [comment] 2021-01-21 16:44
Please use the "Reload Ackee" button in the error modal. The error might be caused by cached data. I otherwise need a few more details to debug this properly.

**Comment by productfrontenddeveloper** [comment] 2021-01-21 16:46
1. Reload and some problem.
2.  and update 3.0.1, some problem. 
3. Clear cache and deploy netlify. some problem.

**Comment by BrookeDot** [comment] 2021-01-21 17:56
I'm also seeing this, for me it happens right after login. The Dashboard loads for a moment then the error appears. Here's the stack trace:

```
mongo    | {"t":{"$date":"2021-01-21T17:53:27.019+00:00"},"s":"I",  "c":"NETWORK",  "id":REMOVED,   "ctx":"conn15","msg":"Connection ended","attr":{"remote":"REMOVED","connectionId":15,"connectionCount":12}}
ackee    | [Ackee] › ✖  fatal     Error: Cannot return null for non-nullable field Size.id.
ackee    |     at completeValue (/srv/app/node_modules/graphql/execution/execute.js:561:13)
ackee    |     at resolveField (/srv/app/node_modules/graphql/execution/execute.js:474:19)
ackee    |     at executeFields (/srv/app/node_modules/graphql/execution/execute.js:294:18)
ackee    |     at collectAndExecuteSubfields (/srv/app/node_modules/graphql/execution/execute.js:749:10)
ackee    |     at completeObjectValue (/srv/app/node_modules/graphql/execution/execute.js:739:10)
ackee    |     at completeValue (/srv/app/node_modules/graphql/execution/execute.js:592:12)
ackee    |     at completeValue (/srv/app/node_modules/graphql/execution/execute.js:558:21)
ackee    |     at /srv/app/node_modules/graphql/execution/execute.js:626:25
ackee    |     at from (<anonymous>)
ackee    |     at completeListValue (/srv/app/node_modules/graphql/execution/execute.js:613:49)
ackee    |     at completeValue (/srv/app/node_modules/graphql/execution/execute.js:574:12)
ackee    |     at /srv/app/node_modules/graphql/execution/execute.js:471:16
ackee    |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
ackee    |     at async Promise.all (index 0)
ackee    |     at async Promise.all (index 3)
```

Looks like something in GraphQL is failing.

**Comment by electerious** [comment] 2021-01-21 18:00
That's interesting. It doesn't seem to be an issue for the demo page, my personal installation and the vercel version. I'm currently looking into it. Help is welcome!

**Comment by electerious** [comment] 2021-01-21 18:04
I'm open for suggestions in the Ackee Gitter chat: https://gitter.im/electerious-Ackee/community

**Comment by electerious** [comment] 2021-01-21 19:06
The good thing: Ackee keeps tracking even when seeing this error. It's just the UI that can't get some data.

---

It seems that Ackee can't query BROWSER_RESOLUTION, BROWSER_WIDTH and and BROWSER_HEIGHT for some records. This could be the case when a record has data it shouldn't have. I sadly can't test it as it doesn't happen on my installation.

There's now a temporary fix (untested) on the develop branch until I can investigate further. It can be installed using the Docker `develop` tag (use `electerious/ackee:develop` instead of `electerious/ackee` when using Docker)

**Comment by BrookeDot** [comment] 2021-01-21 19:31
💥 the temporary fix worked! Thanks for the quick fix, I'll send some coffee your way. 

As expected, I see `1x 0px` for the one domain I was experience the problem on:

<img width="600" alt="Screen Shot 2021-01-21 at 11 29 47 AM" src="https://user-images.githubusercontent.com/150348/105402372-311f4e00-5bdc-11eb-81ed-be60a0e086a9.png">

**Comment by electerious** [comment] 2021-01-21 19:39
@BrookeDot Thanks for the help and thanks for letting me know!

I've deployed the temporary fix on the master branch. It will be available in ~30min via Docker. I will take a closer look at the real issue this weekend!

**Comment by productfrontenddeveloper** [comment] 2021-01-21 19:45
3.0.2 update fixed. Thank you

**Comment by electerious** [comment] 2021-01-23 15:57
I've deployed a non temporary workaround on the develop branch. The tests are now covering the issue.

@BrookeDot Could you try the development branch again to check if everything is still ok?

**Comment by BrookeDot** [comment] 2021-01-23 17:54
Looking good @electerious!

<img width="617" alt="Screen Shot 2021-01-23 at 9 53 43 AM" src="https://user-images.githubusercontent.com/150348/105609866-ee3ab300-5d60-11eb-8689-ac3b3d7c7782.png">

**Comment by BrookeDot** [comment] 2021-01-24 18:02
Now that I see the changelog I think we can just close this sounds like your proper fix prevents even logging of the invalid values.

Thanks again for all your work on this. I've updated to 3.0.3 and things are working great!

**Closed** 2021-01-25 08:13 UTC
Labels: bug
